"""Initial migration

Revision ID: ba310eac19d0
Revises: 
Create Date: 2024-07-29 15:53:30.066581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba310eac19d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###
