# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sampledb
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db/sampledb
    volumes:
      - .:/app
